dice function added
thisisflight/js-advanced-1 pull request #2
Opened 2023-11-08 21:43 UTC by thisisflight

2023-11-09 15:37 UTC, Levitinn requested changes
А в этом задании нужно обойтись одной функцией. В твоем случае, решение хоть и понятно, но логика размыта по трем разным функциям, что делает неудобным переиспользование  этой логики

2023-11-09 20:48 UTC, thisisflight commented
поправил, оставил одну функцию

2023-11-13 19:52 UTC, Levitinn approved these changes
это хорошо)

2023-11-13 19:52 UTC, Levitinn commented on 2-dice/homework.js
> +  console.log(`Получен dice: ${dice}`);
консоль логи нужно стирать перед МР. это засоряет код

2023-11-14 07:39 UTC, merged